# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: keycloak-virtual-service
# spec:
#   hosts:
#   - "d13h57e865tcyq.cloudfront.net"
#   gateways:
#   - bookinfo-gateway
#   http:
#   - route:
#     - destination:
#         host: "keycloak.default.svc.cluster.local"
#         port:
#           number: 80
#     headers:
#       response:
#         set:
#           x-forwarded-proto: https

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-virtual-service
  namespace: "default"
spec:
  hosts:
  - "d13h57e865tcyq.cloudfront.net"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: "/"
    route:
    - destination:
        host: keycloak
        port:
          number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https
    corsPolicy:
      allowOrigins:
      - exact: "*"
      allowCredentials: true
      allowHeaders: ["*"]
