apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: bookinfo-request-auth
spec:
  selector:
    matchLabels:
      app: productpage
  jwtRules:
  - issuer: "http://d13h57e865tcyq.cloudfront.net/realms/Istio"
    jwksUri: "https://d13h57e865tcyq.cloudfront.net/realms/Istio/protocol/openid-connect/certs"